# Generated by Django 4.0 on 2022-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typeclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('téléphone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('siteweb', models.CharField(max_length=200, null=True)),
                ('boite_postale', models.CharField(max_length=200, null=True)),
                ('nif', models.CharField(max_length=200)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionclient.typeclient')),
            ],
        ),
    ]
