# Generated by Django 4.0 on 2022-02-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0003_categoryequipement_catservice_constructeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionclient.client'),
        ),
        migrations.DeleteModel(
            name='HomologationEquipement',
        ),
    ]
