# Generated by Django 4.0 on 2022-02-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0004_equipement_client_delete_homologationequipement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RubriqueFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauxNonCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionclient.client')),
                ('materiel', models.ManyToManyField(to='gestionclient.Materiel')),
                ('rubrique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionclient.rubriquefacturation')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionclient.typemateriel'),
        ),
    ]
