# Generated by Django 4.0 on 2022-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0005_materiel_rubriquefacturation_typemateriel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='quantite',
        ),
    ]
