# Generated by Django 4.0 on 2022-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0007_remove_reseauxnoncommercial_rubrique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Aeronef',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Aeronotique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Maritime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Q_ERFP_classe_B',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Q_ERFP_classe_C',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Q_HF',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Q_UHF',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Q_VHF',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Radio_amateur',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Relais',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Telephone_satellitaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='Terrienne',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reseauxnoncommercial',
            name='VSAT',
            field=models.IntegerField(null=True),
        ),
    ]
