# Generated by Django 4.0 on 2022-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0012_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Aucun', 'Aucun'), ('VHF-UHF', 'VHF-UHF'), ('HF', 'HF'), ('International', 'International'), ('National', 'National'), ('Province', 'Province'), ('Local', 'Local'), ('Numero long', 'Numero long'), ('Numero court', 'Numero court'), ("Codes attribues par l'ARCT", "Codes attribues par l'ARCT"), ('Terminaux simples et de faible puissance', 'Terminaux simples et de faible puissance'), ('Terminaux simples et de faible puissance/Terminaux de communication', 'Terminaux simples et de faible puissance/Terminaux de communication'), ('Terminaux radioelectriques des reseaux', 'Terminaux radioelectriques des reseaux')], default='Aucun', max_length=200, null=True),
        ),
    ]
