# Generated by Django 4.0.2 on 2022-02-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0013_alter_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
    ]
