# Generated by Django 4.0.2 on 2022-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0015_client_status_personnecontact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatAgrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Vendeur', 'Vendeur'), ('Distributeur', 'Distributeur'), ('Installateur', 'Installateur')], max_length=200, null=True)),
                ('nature', models.CharField(choices=[('Nouveau Certificat', 'Nouveau Certificat'), ('Renouvellement Certificat', 'Renouvellement Certificat')], max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.personnecontact')),
            ],
        ),
    ]
