# Generated by Django 4.0.2 on 2022-02-26 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0019_alter_certificatagrement_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatagrement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client'),
        ),
        migrations.AlterField(
            model_name='certificatagrement',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 26), null=True),
        ),
    ]
