# Generated by Django 4.0.2 on 2022-02-26 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0020_alter_certificatagrement_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatagrement',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 26, 19, 22, 47, 323617, tzinfo=utc), null=True),
        ),
    ]
