# Generated by Django 4.0 on 2022-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0021_alter_certificatagrement_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CertificatAgrement',
        ),
    ]
