# Generated by Django 4.0 on 2022-03-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0022_lenon_delete_certificatagrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertAgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Vendeur', 'Vendeur'), ('Installateur', 'Installateur'), ('Distributeur', 'Distributeur')], max_length=200, null=True)),
                ('nature', models.CharField(choices=[('Nouveau certificat', 'Nouveau certificat'), ('Renouvellement certificat', 'Renouvellement certificat')], max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.personnecontact')),
            ],
        ),
        migrations.DeleteModel(
            name='Lenon',
        ),
    ]
