# Generated by Django 4.0 on 2022-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0023_certagr_delete_lenon'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='date_attribution',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
