# Generated by Django 4.0 on 2022-03-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0024_certagr_date_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnecontact',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client'),
        ),
    ]
