# Generated by Django 4.0 on 2022-03-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0026_remove_certagr_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certagr',
            name='date_attribution',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
