# Generated by Django 4.0 on 2022-03-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0028_alter_certagr_date_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certagr',
            name='date_attribution',
            field=models.DateField(null=True),
        ),
    ]
