# Generated by Django 4.0 on 2022-03-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0029_alter_certagr_date_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certagr',
            name='date_attribution',
        ),
    ]
