# Generated by Django 4.0 on 2022-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0030_remove_certagr_date_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='dateAttribution',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
