# Generated by Django 4.0 on 2022-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0031_certagr_dateattribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certagr',
            name='dateAttribution',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
