# Generated by Django 4.0 on 2022-03-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0032_alter_certagr_dateattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.personnecontact'),
        ),
        migrations.AlterField(
            model_name='personnecontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client'),
        ),
    ]
