# Generated by Django 4.0 on 2022-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0033_certagr_contact_alter_personnecontact_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certagr',
            name='dateAttribution',
        ),
        migrations.AddField(
            model_name='certagr',
            name='dateExp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certagr',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
