# Generated by Django 4.0 on 2022-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0034_remove_certagr_dateattribution_certagr_dateexp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certagr',
            name='date_created',
        ),
        migrations.AddField(
            model_name='certagr',
            name='dateAttri',
            field=models.DateField(null=True),
        ),
    ]
