# Generated by Django 4.0 on 2022-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0036_alter_personnecontact_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
    ]
