# Generated by Django 4.0 on 2022-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0037_certagr_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='afficher',
            field=models.CharField(default='oui', max_length=200, null=True),
        ),
    ]
