# Generated by Django 4.0 on 2022-03-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0038_certagr_afficher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certagr',
            name='afficher',
        ),
    ]
