# Generated by Django 4.0 on 2022-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0039_remove_certagr_afficher'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='pourfacturation',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
