# Generated by Django 4.0 on 2022-03-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0042_category_certagr_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.FloatField(max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='certagr',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='factureCertAgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
