# Generated by Django 4.0 on 2022-03-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0043_taux_certagr_facturer_facturecertagr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='factureCertAgr',
        ),
    ]
