# Generated by Django 4.0 on 2022-03-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0044_delete_facturecertagr'),
    ]

    operations = [
        migrations.CreateModel(
            name='factureCertAgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.category')),
                ('certificat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.certagr')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
