# Generated by Django 4.0 on 2022-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0045_facturecertagr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
