# Generated by Django 4.0 on 2022-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0046_alter_taux_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
