# Generated by Django 4.0 on 2022-03-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0047_alter_taux_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecertagr',
            name='category',
        ),
    ]
