# Generated by Django 4.0 on 2022-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0048_remove_facturecertagr_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturecertagr',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
