# Generated by Django 4.0 on 2022-03-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0050_certconf_remove_exploite_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('téléphone', models.CharField(max_length=200, null=True)),
                ('fax', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=200)),
                ('pays_origine', models.CharField(max_length=200)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('constructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.constructeur')),
            ],
        ),
        migrations.CreateModel(
            name='HomologationEqui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Terminal Simple et de Faible Puissance', 'Terminal Simple et de Faible Puissance'), ("Terminal Simple et de Faible Puissance/Terminal de communication d'Entreprise", "Terminal Simple et de Faible Puissance/Terminal de communication d'Entreprise"), ('Terminal Radioelectrique de Reseau', 'Terminal Radioelectrique de Reseau')], max_length=200, null=True)),
                ('dateAttri', models.DateField(null=True)),
                ('dateExp', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.equipement')),
            ],
        ),
    ]
