# Generated by Django 4.0 on 2022-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0051_constructeur_equipement_homologationequi'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructeur',
            name='date_creation',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
