# Generated by Django 4.0 on 2022-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0052_constructeur_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='date_creation',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
