# Generated by Django 4.0 on 2022-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0053_equipement_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologationequi',
            name='nature',
            field=models.CharField(choices=[('Nouveau certificat', 'Nouveau certificat'), ('Renouvellement certificat', 'Renouvellement certificat')], max_length=200, null=True),
        ),
    ]
