# Generated by Django 4.0 on 2022-03-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0054_homologationequi_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Autre', 'Autre'), ('FAI', 'FAI'), ('FSVA', 'FSVA'), ('Public', 'Public'), ('Operateur telephonique', 'Operateur telephonique')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='numeroCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Code Ordinaire', 'Code Ordinaire'), ('USSD', 'USSD'), ('Code Mnemonique', 'Code Mnemonique'), ('ISPC', 'ISPC'), ('NSPC', 'NSPC'), ('MNC', 'MNC'), ('Code de preselection pour les transporteurs internationaux', 'Code Mnemonique')], max_length=200, null=True)),
                ('numero', models.CharField(max_length=200)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
    ]
