# Generated by Django 4.0 on 2022-03-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0055_alter_client_type_numerocourt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq', models.CharField(max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.CreateModel(
            name='AB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.CharField(max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('pq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.pq')),
            ],
        ),
    ]
