# Generated by Django 4.0 on 2022-03-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0056_pq_ab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.CreateModel(
            name='Megas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megas', models.CharField(max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenceRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bande', models.CharField(max_length=200, null=True)),
                ('bande_attribuee', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.CreateModel(
            name='FaisceauxHertzien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bande', models.CharField(max_length=200, null=True)),
                ('bande_passante', models.CharField(max_length=200, null=True)),
                ('nombre_canaux', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.CreateModel(
            name='ChiffreAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.CharField(max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
    ]
