# Generated by Django 4.0 on 2022-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0057_minutes_megas_frequenceradio_faisceauxhertzien_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='certagr',
            options={'ordering': ['-dateAttri']},
        ),
        migrations.AlterModelOptions(
            name='certconf',
            options={'ordering': ['-dateAttri']},
        ),
        migrations.AlterModelOptions(
            name='chiffreaffaire',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='constructeur',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='faisceauxhertzien',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='frequenceradio',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='homologationequi',
            options={'ordering': ['-dateAttri']},
        ),
        migrations.AlterModelOptions(
            name='megas',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='minutes',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='numerocourt',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='pq',
            options={'ordering': ['-dateAtri']},
        ),
        migrations.AddField(
            model_name='faisceauxhertzien',
            name='dateAtri',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faisceauxhertzien',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frequenceradio',
            name='dateAtri',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='frequenceradio',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chiffreaffaire',
            name='ca',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande_passante',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='nombre_canaux',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frequenceradio',
            name='bande',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='frequenceradio',
            name='bande_attribuee',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='megas',
            name='megas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
