# Generated by Django 4.0 on 2022-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0058_alter_ab_options_alter_certagr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande_passante',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='frequenceradio',
            name='bande',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
