# Generated by Django 4.0 on 2022-03-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0059_alter_faisceauxhertzien_bande_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiffreaffaire',
            options={'ordering': ['client', 'dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='frequenceradio',
            options={'ordering': ['client']},
        ),
    ]
