# Generated by Django 4.0 on 2022-03-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0060_alter_chiffreaffaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='nombre_canaux',
            field=models.IntegerField(null=True),
        ),
    ]
