# Generated by Django 4.0 on 2022-03-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0061_alter_faisceauxhertzien_nombre_canaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiffreaffaire',
            options={'ordering': ['client__nom', 'dateAtri']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequenceradio',
            options={'ordering': ['client__nom', 'bande', '-dateAtri']},
        ),
    ]
