# Generated by Django 4.0 on 2022-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0063_ffnumero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffnumero',
            name='FSVA_agrement_equipement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ffnumero',
            name='FSVA_autorisation_arct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ffnumero',
            name='FSVA_etude_dossier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ffnumero',
            name='RN_etude_dossier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ffnumero',
            name='RN_frais_gestion',
            field=models.BooleanField(default=False),
        ),
    ]
