# Generated by Django 4.0 on 2022-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0064_ffnumero_fsva_agrement_equipement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffnumero',
            name='q_cpti',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_ispc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_mnc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_mnemonique',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_nspc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_ordinaire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_pq',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffnumero',
            name='q_ussd',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
