# Generated by Django 4.0 on 2022-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0065_alter_ffnumero_q_cpti_alter_ffnumero_q_ispc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ffnumero',
            old_name='FSVA_autorisation_arct',
            new_name='autorisation_arct',
        ),
        migrations.RemoveField(
            model_name='ffnumero',
            name='FSVA_etude_dossier',
        ),
        migrations.RemoveField(
            model_name='ffnumero',
            name='RN_etude_dossier',
        ),
        migrations.RemoveField(
            model_name='ffnumero',
            name='RN_frais_gestion',
        ),
    ]
