# Generated by Django 4.0 on 2022-03-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0066_rename_fsva_autorisation_arct_ffnumero_autorisation_arct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FFNumero',
        ),
    ]
