# Generated by Django 4.0 on 2022-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0068_ffnumero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffnumero',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ffnumero',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
