# Generated by Django 4.0 on 2022-03-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0070_ffnumero_dateatri'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF_Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_pq', models.IntegerField(default=0, null=True)),
                ('q_ordinaire', models.IntegerField(default=0, null=True)),
                ('q_ussd', models.IntegerField(default=0, null=True)),
                ('q_mnemonique', models.IntegerField(default=0, null=True)),
                ('q_mnc', models.IntegerField(default=0, null=True)),
                ('q_nspc', models.IntegerField(default=0, null=True)),
                ('q_ispc', models.IntegerField(default=0, null=True)),
                ('q_cpti', models.IntegerField(default=0, null=True)),
                ('RN_etudeDossier', models.BooleanField(default=False)),
                ('RN_fraisGestion', models.BooleanField(default=False)),
                ('RN_redevanceAnn', models.BooleanField(default=False)),
                ('nature', models.CharField(choices=[('Nouveau Client', 'Nouveau Client'), ('Renouvellement Client', 'Renouvellement Client')], max_length=200, null=True)),
                ('facturer', models.CharField(default='non', max_length=200, null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('dateAtri', models.DateField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.DeleteModel(
            name='FFNumero',
        ),
    ]
