# Generated by Django 4.0 on 2022-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0072_ff_numero_fs_agreequipe_ff_numero_fs_autoarct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocourt',
            name='dateAtri',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pq',
            name='dateAtri',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
