# Generated by Django 4.0 on 2022-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0073_alter_numerocourt_dateatri_alter_pq_dateatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerocourt',
            name='ffnumero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.ff_numero'),
        ),
    ]
