# Generated by Django 4.0 on 2022-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0075_pq_ffnumero_alter_numerocourt_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ff_numero',
            name='nature',
            field=models.CharField(choices=[('Client Nouveau ', 'Client Nouveau '), ('Client Existant', 'Client Existant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='numerocourt',
            name='type',
            field=models.CharField(choices=[('Code Ordinaire', 'Code Ordinaire'), ('USSD', 'USSD'), ('Code Mnemonique', 'Code Mnemonique'), ('ISPC', 'ISPC'), ('NSPC', 'NSPC'), ('MNC', 'MNC'), ('Code de preselection pour les transporteurs internationaux', 'Code de preselection pour les transporteurs internationaux')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pq',
            name='dateAtri',
            field=models.DateField(null=True),
        ),
    ]
