# Generated by Django 4.0 on 2022-03-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0076_alter_ff_numero_nature_alter_numerocourt_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifFFNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.FloatField(max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture_FFNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
                ('ffnumero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.ff_numero')),
                ('taux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
