# Generated by Django 4.0 on 2022-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0077_tarifffnumero_taux_facture_ffnumero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifffnumero',
            name='FS_agreEquipe',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='FS_autoARCT',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='FS_etudeDossier',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='RN_etudeDossier',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='RN_fraisGestion',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='RN_redevanceAnn',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_cpti',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_ispc',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_mnc',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_mnemonique',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_nspc',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_ordinaire',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_pq',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='q_ussd',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarifffnumero',
            name='pq',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
