# Generated by Django 4.0 on 2022-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0078_tarifffnumero_fs_agreequipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='pq',
        ),
        migrations.AddField(
            model_name='facture_ffnumero',
            name='dateAtri',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facture_ffnumero',
            name='total',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='dateAtri',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
