# Generated by Django 4.0 on 2022-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0079_remove_tarifffnumero_pq_facture_ffnumero_dateatri_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taux',
            old_name='date',
            new_name='dateAtri',
        ),
    ]
