# Generated by Django 4.0 on 2022-03-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0080_rename_date_taux_dateatri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateField(null=True),
        ),
    ]
