# Generated by Django 4.0 on 2022-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0082_alter_taux_dateatri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifffnumero',
            old_name='FS_agreEquipe',
            new_name='etudeDossier',
        ),
        migrations.RenameField(
            model_name='tarifffnumero',
            old_name='FS_autoARCT',
            new_name='fraisGestion',
        ),
        migrations.RenameField(
            model_name='tarifffnumero',
            old_name='FS_etudeDossier',
            new_name='redevanceAnn',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='RN_etudeDossier',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='RN_fraisGestion',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='RN_redevanceAnn',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_cpti',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_ispc',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_mnc',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_mnemonique',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_nspc',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_ordinaire',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_pq',
        ),
        migrations.RemoveField(
            model_name='tarifffnumero',
            name='q_ussd',
        ),
        migrations.AddField(
            model_name='tarifffnumero',
            name='type',
            field=models.CharField(choices=[('PQ', 'PQ'), ('Code Ordinaire', 'Code Ordinaire'), ('USSD', 'USSD'), ('Code Mnemonique', 'Code Mnemonique'), ('ISPC', 'ISPC'), ('NSPC', 'NSPC'), ('MNC', 'MNC'), ('Code de preselection pour les transporteurs internationaux', 'Code de preselection pour les transporteurs internationaux')], max_length=200, null=True),
        ),
    ]
