# Generated by Django 4.0 on 2022-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0084_tariffsvanumero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ff_numero',
            name='efacturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
