# Generated by Django 4.0 on 2022-03-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0086_remove_facture_ffnumero_client_ff_numero_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_ffnumero',
            name='q_pq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifffnumero'),
        ),
    ]
