# Generated by Django 4.0 on 2022-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0088_facture_ffnumero_fsva_facture_ffnumero_q_cpti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ff_numero',
            name='dateFin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ff_numero',
            name='observation',
            field=models.TextField(default='-', max_length=300, null=True),
        ),
    ]
