# Generated by Django 4.0 on 2022-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0089_ff_numero_datefin_ff_numero_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ff_numero',
            name='dateFin',
            field=models.DateField(default='', null=True),
        ),
    ]
