# Generated by Django 4.0 on 2022-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0092_facture_ffnumero_total_bif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='fsva',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_cpti',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_ispc',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_mnc',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_mnemonique',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_nspc',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_ordinaire',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_pq',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='q_ussd',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='total',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture_ffnumero',
            name='total_bif',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
