# Generated by Django 4.0 on 2022-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0094_alter_facture_ffnumero_fsva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='porfact',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
