# Generated by Django 4.0 on 2022-03-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0095_certagr_porfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifAgre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.CharField(choices=[('Vendeur', 'Vendeur'), ('Distributeur', 'Distributeur'), ('Installateur', 'Installateur')], max_length=200, null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture_CertAgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('total_bif', models.IntegerField(null=True)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.certagr')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifagre')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
