# Generated by Django 4.0 on 2022-03-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0097_facture_certagr_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifagre',
            old_name='tarif',
            new_name='type',
        ),
    ]
