# Generated by Django 4.0 on 2022-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0098_rename_tarif_tarifagre_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifagre',
            name='tarif',
            field=models.IntegerField(null=True),
        ),
    ]
