# Generated by Django 4.0 on 2022-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0101_certagr_facturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifagre',
            old_name='tarif',
            new_name='tarifs',
        ),
    ]
