# Generated by Django 4.0 on 2022-03-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0102_rename_tarif_tarifagre_tarifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_certagr',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client'),
        ),
    ]
