# Generated by Django 4.0 on 2022-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0104_remove_facture_certagr_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='certconf',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certconf',
            name='pourfact',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
