# Generated by Django 4.0 on 2022-03-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0105_certconf_facturer_certconf_pourfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESEAU LOCAL', 'RESEAU LOCAL'), ('RESEAU NATIONAL', 'RESEAU NATIONAL')], max_length=200, null=True)),
                ('tarif', models.IntegerField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('total_bif', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.certconf')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifconf')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
