# Generated by Django 4.0 on 2022-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0106_tarifconf_factureconf'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologationequi',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homologationequi',
            name='pourfact',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
