# Generated by Django 4.0 on 2022-03-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0108_tarifhom_alter_factureconf_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureconf',
            name='certificat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.certconf'),
        ),
        migrations.AlterField(
            model_name='factureconf',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifconf'),
        ),
        migrations.CreateModel(
            name='FactureHom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('total_bif', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.homologationequi')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifhom')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
