# Generated by Django 4.0 on 2022-03-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0109_alter_factureconf_certificat_alter_factureconf_tarif_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactureHom',
        ),
    ]
