# Generated by Django 4.0 on 2022-03-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0110_delete_facturehom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifHom',
        ),
    ]
