# Generated by Django 4.0 on 2022-03-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0111_delete_tarifhom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifHom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Terminal Simple et de Faible Puissance', 'Terminal Simple et de Faible Puissance'), ("Terminal Simple et de Faible Puissance/Terminal de communication d'Entreprise", "Terminal Simple et de Faible Puissance/Terminal de communication d'Entreprise"), ('Terminal Radioelectrique de Reseau', 'Terminal Radioelectrique de Reseau')], max_length=200, null=True)),
                ('tarif', models.IntegerField(null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureHom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('total_bif', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.homologationequi')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tarifhom')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
