# Generated by Django 4.0 on 2022-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0113_numerocourt_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taux',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ff_numero',
            name='dateAtri',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ff_numero',
            name='nature',
            field=models.CharField(choices=[('Client Nouveau', 'Client Nouveau'), ('Client Existant', 'Client Existant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
