# Generated by Django 4.0 on 2022-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0114_taux_updated_alter_ff_numero_dateatri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taux',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
