# Generated by Django 4.0 on 2022-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0115_alter_taux_dateatri_alter_taux_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taux',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
