# Generated by Django 4.0 on 2022-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0116_alter_taux_dateatri_alter_taux_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifffnumero',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
