# Generated by Django 4.0 on 2022-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0118_alter_taux_dateatri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
