# Generated by Django 4.0 on 2022-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0119_alter_taux_dateatri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taux',
            name='updated',
        ),
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
