# Generated by Django 4.0 on 2022-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0123_alter_taux_dateatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='taux',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taux',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
