# Generated by Django 4.0 on 2022-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0124_taux_updated_alter_taux_dateatri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifhom',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
