# Generated by Django 4.0 on 2022-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0125_alter_tarifhom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifagre',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
