# Generated by Django 4.0 on 2022-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0126_alter_tarifagre_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifconf',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
