# Generated by Django 4.0.3 on 2022-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0127_alter_tarifconf_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faisceauxhertzien',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequenceradio',
            options={},
        ),
        migrations.AddField(
            model_name='faisceauxhertzien',
            name='efacturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faisceauxhertzien',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frequenceradio',
            name='efacturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frequenceradio',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
