# Generated by Django 4.0.3 on 2022-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0129_tariffh_alter_faisceauxhertzien_dateatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffh',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
    ]
