# Generated by Django 4.0.3 on 2022-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0130_tariffh_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffh',
            name='nature',
            field=models.CharField(choices=[(23, '> 23'), (13, '> 13'), (3, '> 3'), (0, '> 0')], max_length=200, null=True),
        ),
    ]
