# Generated by Django 4.0.3 on 2022-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0131_tariffh_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffh',
            name='nature',
            field=models.CharField(choices=[(23, 23), (13, 13), (3, 3), (0, 0)], max_length=200, null=True),
        ),
    ]
