# Generated by Django 4.0.3 on 2022-04-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0133_alter_tariffh_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffh',
            name='repere',
        ),
    ]
