# Generated by Django 4.0.3 on 2022-04-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0136_tariffh_dateatri_alter_tariffh_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffh',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
