# Generated by Django 4.0.3 on 2022-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0137_alter_tariffh_dateatri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffh',
            name='nature',
            field=models.IntegerField(choices=[(23, '>23 Ghz'), (13, '>13 Ghz'), (3, '>3 Ghz'), (0, '<3 Ghz')], null=True),
        ),
    ]
