# Generated by Django 4.0 on 2022-04-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0138_alter_tariffh_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffh',
            name='p_canal',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariffh',
            name='p_mhz',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Facture_FH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bif', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
                ('faisceaux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.faisceauxhertzien')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.tariffh')),
                ('taux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
