# Generated by Django 4.0 on 2022-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0139_alter_tariffh_p_canal_alter_tariffh_p_mhz_facture_fh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffh',
            name='p_canal',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tariffh',
            name='p_mhz',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
