# Generated by Django 4.0 on 2022-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0140_alter_tariffh_p_canal_alter_tariffh_p_mhz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faisceauxhertzien',
            name='bande_passante',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
