# Generated by Django 4.0 on 2022-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0141_alter_faisceauxhertzien_bande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture_FH_annuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
