# Generated by Django 4.0 on 2022-04-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0142_facture_fh_annuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='taux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux'),
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='total_bif',
            field=models.IntegerField(null=True),
        ),
    ]
