# Generated by Django 4.0 on 2022-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0143_facture_fh_annuelle_dateatri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='efacturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='etat',
            field=models.CharField(default='actif', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
