# Generated by Django 4.0 on 2022-04-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0144_facture_fh_annuelle_efacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listeFH_Annuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
                ('etat', models.CharField(default='actif', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facture_fh_annuelle',
            name='faisceaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.listefh_annuelle'),
        ),
    ]
