# Generated by Django 4.0 on 2022-04-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0146_listefh_annuelle_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeFHAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faisceaux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.faisceauxhertzien')),
            ],
        ),
        migrations.CreateModel(
            name='Repere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repere', models.DateField(null=True)),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
        migrations.RemoveField(
            model_name='listefh_annuelle',
            name='client',
        ),
        migrations.DeleteModel(
            name='Facture_FH_annuelle',
        ),
        migrations.DeleteModel(
            name='listeFH_Annuelle',
        ),
        migrations.AddField(
            model_name='listefhannuelle',
            name='repere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.repere'),
        ),
    ]
