# Generated by Django 4.0 on 2022-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0147_listefhannuelle_repere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repere',
            name='efacturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repere',
            name='facturer',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
