# Generated by Django 4.0 on 2022-04-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0148_repere_efacturer_repere_facturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture_FH_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bif', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
                ('repere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.repere')),
                ('taux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionclient.taux')),
            ],
        ),
    ]
