# Generated by Django 4.0 on 2022-04-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0149_facture_fh_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('etat', models.CharField(default='actif', max_length=200)),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client')),
            ],
        ),
    ]
