# Generated by Django 4.0 on 2022-04-24 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0150_client_dateatri_personnecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnecontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionclient.client'),
        ),
    ]
