# Generated by Django 4.0 on 2022-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0151_alter_personnecontact_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DREF', 'DREF'), ('DG', 'DG'), ('Chef Service Normalisation,Reseaux et Servicess', 'Chef Service Normalisation,Reseaux et Servicess'), ('Chef Service a.i Normalisation,Reseaux et Servicess', 'Chef Service a.i Normalisation,Reseaux et Servicess')], max_length=200, null=True)),
                ('etat', models.CharField(default='actif', max_length=200)),
                ('dateAtri', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
