# Generated by Django 4.0 on 2022-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0152_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='etat',
            field=models.CharField(default='deactif', max_length=200),
        ),
        migrations.AlterField(
            model_name='direction',
            name='type',
            field=models.CharField(choices=[('DREF', 'DREF'), ('DG', 'DG'), ('Chef Service Normalisation,Reseaux et Servicess', 'Chef Service Normalisation,Reseaux et Servicess')], max_length=200, null=True),
        ),
    ]
