# Generated by Django 4.0 on 2022-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0153_alter_direction_etat_alter_direction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructeur',
            name='date_creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='date_creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
