# Generated by Django 4.0.2 on 2022-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0155_alter_numerocourt_dateatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='certagr',
            name='dejaRenou',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ab',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Autre', 'Autre'), ('FAI', 'FAI'), ('FSVA', 'FSVA'), ('Public', 'Public'), ('Opérateur téléphonique', 'Opérateur téléphonique')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pq',
            name='dateAtri',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
