# Generated by Django 4.0.2 on 2022-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclient', '0158_alter_ff_numero_dateatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='certconf',
            name='dejaRenou',
            field=models.CharField(default='non', max_length=200, null=True),
        ),
    ]
